image: ubuntu:xenial

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - echo "Building the app"

deploy_prod:
  stage: deploy
  script:
    - ls -lah .
  environment:
    name: production
    url: https://test53.com
  when: manual
  only:
  - master
